language: rust
rust: nightly
cache: cargo
install: skip
script: skip
jobs:
  include:
    - script:
      - rustup -v component add rustfmt-preview
      - cargo -v fmt --all -- --check
    - script:
      - rustup -v component add clippy-preview
      - rustup -v target add wasm32-unknown-unknown
      - cargo -v clippy --all --all-features --all-targets -- -D warnings
    - script:
      - rustup -v target add wasm32-unknown-unknown
      - cargo -v install -f cargo-web
      - cargo -v web test --all-features --target wasm32-unknown-unknown
